ktor {
    deployment {
        port = 8080
        port = ${?PORT}
        host = "0.0.0.0"
        host = ${?HOST}
    }
    application {
        modules = [ com.example.groceryapp.ApplicationKt.module ]
    }
}

jwt {
    secret = "secret"
    secret = ${?JWT_SECRET}
    issuer = "http://192.168.0.102:8080"
    issuer = ${?JWT_ISSUER}
    audience = "http://192.168.0.102:8080/grocery"
    audience = ${?JWT_AUDIENCE}
    realm = "Access to 'grocery'"
}

mongodb {
    uri = "mongodb+srv://smartgrocery:admin123@cluster0.b3gdydm.mongodb.net/?appName=Cluster0"
    uri = ${?MONGODB_URI}
    database = "grocery_db"
    database = ${?MONGODB_DATABASE}
}

firebase {
    serviceAccountPath = "firebase-service-account.json"
    serviceAccountPath = ${?FIREBASE_SERVICE_ACCOUNT_PATH}
}
